Changed meets to claims to meet in section 3.7
w3c/publ-a11y pull request #219
Opened 2023-11-30 18:32 UTC by GeorgeKerscher

I made all changes in section 3.7 I did not go through the whole document. Next time a full language review pass is done, we should look for any remaining meets statements.

2023-11-30 18:35 UTC, clapierre approved these changes
looks good

2023-11-30 19:34 UTC, mattgarrish requested changes

2023-11-30 19:34 UTC, mattgarrish commented on UX-Guide-Metadata/draft/principles/index.html
> +					<aside class="example" title="Conformance statements that claims to meet minimum accessibility standards followed by detailed conformance information">
I think the change here is correct but "statements" in the title attribute should be singular:

> Conformance statement that claims to meet

2023-12-01 11:08 UTC, gregoriopellegrino approved these changes

2023-12-01 17:21 UTC, merged