Full stop and more
w3c/publ-a11y pull request #441
Opened 2024-10-22 18:58 UTC by GeorgeKerscher

Thank you @Gregorio  the list of full stops made it easy to remove them. That was one commit.
I filed an #issue-438 about the strings and have some disagreements.
I filed an issue 440 about thefourth example in conformance is missing IDs.

I removed a lot more full stops in the last two commits.

I will file an issue that the additional information missing IDs

2024-10-22 19:05 UTC, mattgarrish requested changes

2024-10-22 19:05 UTC, mattgarrish commented on UX-Guide-Metadata/draft/principles/index.html
> +								zooming options</li>
This is highly problematic. Should the strings all be a single statement? Taking a period out of the middle of a paragraph can't be done, and presumably the other period here would have to be removed. Could you use commas here, perhaps, so make it more like:

> Text and page layout cannot be modified as the reading experience is close to a print version, but reading systems can still provide zooming options

2024-10-22 19:20 UTC, GeorgeKerscher commented
I agree. making changes now. Will look for more of these things.

2024-10-22 19:41 UTC, GeorgeKerscher commented
In conformance we have:
Detailed Conformance Information:
This publication claims to meet EPUB Accessibility 1.1 Web Accessibility Content Guidelines (WCAG) 2.1 Level AA The publication was certified on 2021-09-07 by Foo's Accessibility Testing with a credential of "Enterprise Accessibility Rating" For more information, refer to the certifier's report

Would it work better to make these list items? 
 statement that claims to meet accepted accessibility standards followed by detailed conformance information">
						<p data-localization-id="conformance-aa" data-localization-mode="compact">This publication meets
							accepted accessibility standards</p>
						<p>
							<span data-localization-id="conformance-certification-info" data-localization-mode="compact"
								>The publication was certified</span>
							<span data-localization-id="conformance-certifier-prefix" data-localization-mode="compact"
								>by</span> Foo's Accessibility Testing </p>
						<p>

2024-10-22 20:21 UTC, mattgarrish commented
I'm kind of confused reading that section. The examples aren't split like the other with compact and extended descriptions. Each begins with three statements and then a heading "Detailed Conformance Information:" followed by a paragraph.

Is it correct that the first three statements are what you use as the compact statements, or are they examples of what information you use to write the descriptive statement that follows. Also, is it an omission that [example 8](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/#example-unknown-conformance-statement) only has the first three statements and no descriptive statement?

And in example 7,. it says the conformance cannot be identified, but in the descriptive statement there's a placeholder for inserting a publisher's internal conformance standard. Shouldn't that be removed?

But back to your question, if the goal is to omit the periods, I think you have to break the paragraphs up into separate statements. That would let the implementor decide whether to format them as a list or combine them into a paragraph using periods. I don't see any easy way to combine them all into one without making a large run-on sentence.

2024-10-23 08:20 UTC, gregoriopellegrino approved these changes

2024-10-23 13:51 UTC, clapierre approved these changes
Once all merged, we can make sure no period was taken out between paragraphs.

2024-10-23 21:14 UTC, merged